# Application Settings

ENVIRONMENT = "development"

APP_BASE_URL = "http://localhost:8501"

APP_SECRET_KEY = "dev-secret-change-in-production-abc123"

# Supabase Configuration

SUPABASE_URL = "https://yehakxccvnmugkqhtmtj.supabase.co"

SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllaGFreGNjdm5tdWdrcWh0bXRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc0NjAxMzQsImV4cCI6MjA4MzAzNjEzNH0.Rs3qQOrJBuxExl-ayV2QCV2OgYjz4gIdTMGYIECz6OA"

SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllaGFreGNjdm5tdWdrcWh0bXRqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NzQ2MDEzNCwiZXhwIjoyMDgzMDM2MTM0fQ._Zo2nM42ar2ATB7VHyUsjY3kkS0hMdoiHGS1pwHUiY0"

# Stripe Configuration (TEST MODE)

STRIPE_PUBLISHABLE_KEY = "pk_test_51Mr6ZGGLbG2yglsweaRu5t54zXta3icPp6C3qWcAEEI1fYyYpLCUPpxOf3jFwZqyaDy9ZTLMJ285OyxP6sJW4Jmq00WyHKVEaD"

STRIPE_SECRET_KEY = "sk_test_51Mr6ZGGLbG2yglswrQwNzg049VXhqQ0XqyxFYouM2bkqhEvJA5CvBPCAMCjRvnymJV6A924kCETIGqmBPpIX9Wzn00QqFqfPyf"

STRIPE_WEBHOOK_SECRET = "whsec_34edfdf1441d0af35228e2a64eb95d5cf28a369a9303615aa93d9e8ce30adead"

ANNUAL_PAYMENT_LINK = "https://buy.stripe.com/dRm4gz3VbeZt0B36Afao803"  # 

MONTHLY_PAYMENT_LINK = "https://buy.stripe.com/dRm4gz3VbeZt0B36Afao803"  # 
 
# Subscriptions (must be RECURRING)
STRIPE_PRICE_PRO_MONTHLY = "price_1SnqquGLbG2yglswGsfFBV1A"
STRIPE_PRICE_PRO_ANNUAL = "price_1SnqquGLbG2yglswrSzhS4Rc"
STRIPE_PRICE_AGENCY_MONTHLY = "price_1SnqqvGLbG2yglswsw13ibdb"
STRIPE_PRICE_AGENCY_ANNUAL = "price_1SnqqwGLbG2yglsw6Ix9EzKf"
STRIPE_PRICE_ELITE_MONTHLY = "price_1SnqqwGLbG2yglswjs4PwJ87"
STRIPE_PRICE_ELITE_ANNUAL = "price_1SnqqxGLbG2yglsw8eb8p2vT"
STRIPE_PRICE_CREDITS_1000 = "price_1SnqqxGLbG2yglswHGpxNX6u"
STRIPE_PRICE_CREDITS_5000 = "price_1SnqqyGLbG2yglswEyt6SVwv"
STRIPE_PRICE_CREDITS_10000 = "price_1SnqqyGLbG2yglswuvd2JZPy"

# Google AI Configuration

GOOGLE_API_KEY = "AIzaSyAc02xPSoS2qyMp2p1d8OY8GHjYgY6woe0"

# Flask Webhook Server

FLASK_SECRET_KEY = "678d879c20cbe78aaed09bbb902a27b8b75afc45d252ddaabba63b3ab921a8e5"

PORT = "8000"

SMTP_HOST = "smtp.gmail.com"

SMTP_PORT = 587

SMTP_USER = "moroccoboy1990@gmail.com"

SMTP_PASSWORD = "Maslouhi1990"
